--DESAFIO 

/* TABELA: VENDAS_ANALITICAS

RECUPERE UMA QUANTIDADE DE PRODUTOS E MÉDIA DE VENDAS POR FABRICANTE DE ACORDO COM OS CRITÉRIOS ABAIXO

DEVE SER UTILIZADA A COLUNA VENDA_LIQUIDA PARA CALCULAR A MÉDIA ARITMETICA

O FABRICANTE ESTÁ NA TABELA DE PRODUTOS

DEVEM SER EXIBIDAS NO RESULTADO DA CONSULTA AS SEGUINTES COLUNAS

--> CODIGO DO FABRICANTE --> NOME DO FABRICANTE --> QUANTIDADE DE PRODUTOS 
CADASTRADOS PARA O FABRICANTE --> MÉDIA DE VENDAS DO FABRICANTE

CASO O PRODUTO NÃO TENHA FABRICANTE DEVE SER INFORMANDO COM FABRICANTE NÃO IDENTIFICADO

ORDENE PELO FABRICANTE QUE TEM A MELHOR MÉDIA DE VENDAS 

*/

USE PBS_PROCFIT_DADOS

-- Desafio com LEFT JOIN
SELECT COALESCE(CAST(A.FABRICANTE AS VARCHAR(10)), 'NÃO IDENTIFICADO') AS FABRICANTE
	  ,COALESCE(C.NOME, 'NÃO IDENTIFICADO')		  AS NOME_PRODUTO
	  ,COUNT(DISTINCT A.DESCRICAO)				  AS QTDE_PRODUTOS
	  ,AVG(B.VENDA_LIQUIDA)						  AS MEDIA_VENDA_LIQUIDA
FROM PRODUTOS				A
LEFT JOIN 
	VENDAS_ANALITICAS		B ON A.PRODUTO = B.PRODUTO
LEFT JOIN PESSOAS_JURIDICAS	C ON A.FABRICANTE = C.ENTIDADE
GROUP BY
	 A.FABRICANTE
	,C.NOME
ORDER BY
	MEDIA_VENDA_LIQUIDA DESC

-- Desafio com RIGHT JOIN
SELECT B.FABRICANTE							AS PRODUTO
	 , COALESCE(C.NOME, 'NAO IDENTIFICADO') AS NOME_FABRICANTE
	 , COUNT( DISTINCT( B.DESCRICAO ) )		AS QDT_PRODUTOS
	 , AVG(A.VENDA_LIQUIDA)					AS MEDIA_VENDAS
FROM VENDAS_ANALITICAS		A 
RIGHT JOIN PRODUTOS			B
	ON A.PRODUTO = B.PRODUTO
LEFT
JOIN PESSOAS_JURIDICAS		C
	ON B.FABRICANTE = C.ENTIDADE
GROUP BY
	 B.FABRICANTE
	,C.NOME
ORDER BY
	MEDIA_VENDAS DESC
	
-- DESAFIO 

-- BUSQUE TODAS AS VENDAS E TODOS OS CLIENTES QUE AINDA NÃO REALIZARAM COMPRAS. 
-- SUA CONSULTA DEVERÁ TRAZER O CÓD. DO CLIENTE, O NOME DO CLIENTE E O TOTAL VENDIDO (VENDA_LIQUIDA) .

-- SERÁ NECESSÁRIO UTILIZAR AS TABELAS VENDAS_ANALITICAS E ENTIDADES, 
-- ONDE ELAS SE RELACIONAM ATRAVÉS DA COLUNA CLIENTE DA TABELA DE VENDAS_ANALITICAS 
-- E ENTIDADE DA TABELA DE ENTIDADES.

SELECT A.ENTIDADE				AS COD_CLIENTE
	 , A.NOME					AS NOME_CLIENTE
	 , COALESCE(SUM( B.VENDA_LIQUIDA ), 0) AS TOTAL_VENDIDO
FROM ENTIDADES			A
FULL
JOIN VENDAS_ANALITICAS	B
	ON A.ENTIDADE = B.CLIENTE
GROUP BY
	 A.ENTIDADE
	,A.NOME
ORDER BY
	3 DESC

SELECT *
FROM VENDAS_ANALITICAS
 
SELECT FAMILIA_PRODUTO
FROM PRODUTOS


SP_HELP PRODUTOS