--DESAFIO 

/* TABELA: VENDAS_ANALITICAS

RECUPERE UMA QUANTIDADE DE PRODUTOS E MÉDIA DE VENDAS POR FABRICANTE DE ACORDO COM OS CRITÉRIOS ABAIXO

DEVE SER UTILIZADA A COLUNA VENDA_LIQUIDA PARA CALCULAR A MÉDIA ARITMETICA

O FABRICANTE ESTÁ NA TABELA DE PRODUTOS

DEVEM SER EXIBIDAS NO RESULTADO DA CONSULTA AS SEGUINTES COLUNAS

--> CODIGO DO FABRICANTE --> NOME DO FABRICANTE --> QUANTIDADE DE PRODUTOS 
CADASTRADOS PARA O FABRICANTE --> MÉDIA DE VENDAS DO FABRICANTE

CASO O PRODUTO NÃO TENHA FABRICANTE DEVE SER INFORMANDO COM FABRICANTE NÃO IDENTIFICADO

ORDENE PELO FABRICANTE QUE TEM A MELHOR MÉDIA DE VENDAS 

*/

SELECT COALESCE(CAST(A.FABRICANTE AS VARCHAR(10)), 'NÃO IDENTIFICADO') AS FABRICANTE
	  ,COALESCE(C.NOME, 'NÃO IDENTIFICADO')		  AS NOME_PRODUTO
	  ,COUNT(DISTINCT A.DESCRICAO)				  AS QTDE_PRODUTOS
	  ,AVG(B.VENDA_LIQUIDA)						  AS MEDIA_VENDA_LIQUIDA
FROM PRODUTOS				A
LEFT JOIN 
	VENDAS_ANALITICAS		B ON A.PRODUTO = B.PRODUTO
LEFT JOIN PESSOAS_JURIDICAS	C ON A.FABRICANTE = C.ENTIDADE
GROUP BY
	 A.FABRICANTE
	,C.NOME
ORDER BY
	MEDIA_VENDA_LIQUIDA DESC


SELECT FAMILIA_PRODUTO
FROM PRODUTOS

SELECT *
FROM PESSOAS_JURIDICAS

SP_HELP PRODUTOS